// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaEspecialista_IA.Data;

#nullable disable

namespace sistemaEspecialista_IA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322132710_BaseDeConhecimento")]
    partial class BaseDeConhecimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("sistemaEspecialista_IA.Models.Fato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chave = "tem_pelos",
                            Descricao = "Tem pelos"
                        },
                        new
                        {
                            Id = 2,
                            Chave = "da_leite",
                            Descricao = "Dá leite"
                        },
                        new
                        {
                            Id = 3,
                            Chave = "tem_penas",
                            Descricao = "Tem penas"
                        },
                        new
                        {
                            Id = 4,
                            Chave = "pele_umida",
                            Descricao = "Pele úmida"
                        },
                        new
                        {
                            Id = 5,
                            Chave = "respira_agua",
                            Descricao = "Respira debaixo d'água"
                        },
                        new
                        {
                            Id = 6,
                            Chave = "tem_escamas",
                            Descricao = "Tem escamas"
                        },
                        new
                        {
                            Id = 7,
                            Chave = "late",
                            Descricao = "Late"
                        },
                        new
                        {
                            Id = 8,
                            Chave = "mia",
                            Descricao = "Mia"
                        },
                        new
                        {
                            Id = 9,
                            Chave = "muge",
                            Descricao = "Muge"
                        },
                        new
                        {
                            Id = 10,
                            Chave = "relincha",
                            Descricao = "Relincha"
                        },
                        new
                        {
                            Id = 11,
                            Chave = "ruge",
                            Descricao = "Ruge"
                        },
                        new
                        {
                            Id = 12,
                            Chave = "uiva",
                            Descricao = "Uiva"
                        },
                        new
                        {
                            Id = 13,
                            Chave = "come_banana",
                            Descricao = "Come banana"
                        },
                        new
                        {
                            Id = 14,
                            Chave = "tem_tromba",
                            Descricao = "Tem tromba"
                        },
                        new
                        {
                            Id = 15,
                            Chave = "pescoco_longo",
                            Descricao = "Pescoço longo"
                        },
                        new
                        {
                            Id = 16,
                            Chave = "dorme_cabeca_baixo",
                            Descricao = "Dorme de cabeça para baixo"
                        },
                        new
                        {
                            Id = 17,
                            Chave = "solta_esguicho",
                            Descricao = "Solta esguicho de água"
                        },
                        new
                        {
                            Id = 18,
                            Chave = "listras_laranja_pretas",
                            Descricao = "Listras laranjas e pretas"
                        },
                        new
                        {
                            Id = 19,
                            Chave = "listras_brancas_pretas",
                            Descricao = "Listras brancas e pretas"
                        },
                        new
                        {
                            Id = 20,
                            Chave = "manchas_escuras",
                            Descricao = "Manchas escuras"
                        },
                        new
                        {
                            Id = 21,
                            Chave = "cacareja",
                            Descricao = "Cacareja"
                        },
                        new
                        {
                            Id = 22,
                            Chave = "faz_quack",
                            Descricao = "Faz quack"
                        },
                        new
                        {
                            Id = 23,
                            Chave = "pernas_longas",
                            Descricao = "Pernas longas"
                        },
                        new
                        {
                            Id = 24,
                            Chave = "nao_voa",
                            Descricao = "Não voa"
                        },
                        new
                        {
                            Id = 25,
                            Chave = "vive_no_gelo",
                            Descricao = "Vive no gelo"
                        },
                        new
                        {
                            Id = 26,
                            Chave = "caca_do_alto",
                            Descricao = "Caça voando do alto"
                        },
                        new
                        {
                            Id = 27,
                            Chave = "dentes_afiados",
                            Descricao = "Tem dentes afiados"
                        },
                        new
                        {
                            Id = 28,
                            Chave = "nao_tem_pernas",
                            Descricao = "Não tem pernas"
                        },
                        new
                        {
                            Id = 29,
                            Chave = "casco_duro",
                            Descricao = "Tem casco duro"
                        },
                        new
                        {
                            Id = 30,
                            Chave = "faz_croac",
                            Descricao = "Faz croac"
                        },
                        new
                        {
                            Id = 31,
                            Chave = "cor_laranja_branca",
                            Descricao = "Cor laranja e branca"
                        },
                        new
                        {
                            Id = 32,
                            Chave = "e_mamifero",
                            Descricao = "É Mamífero"
                        },
                        new
                        {
                            Id = 33,
                            Chave = "e_ave",
                            Descricao = "É Ave"
                        },
                        new
                        {
                            Id = 34,
                            Chave = "e_reptil",
                            Descricao = "É Réptil"
                        },
                        new
                        {
                            Id = 35,
                            Chave = "e_anfibio",
                            Descricao = "É Anfíbio"
                        },
                        new
                        {
                            Id = 36,
                            Chave = "e_peixe",
                            Descricao = "É Peixe"
                        },
                        new
                        {
                            Id = 37,
                            Chave = "cachorro",
                            Descricao = "Cachorro"
                        },
                        new
                        {
                            Id = 38,
                            Chave = "gato",
                            Descricao = "Gato"
                        },
                        new
                        {
                            Id = 39,
                            Chave = "vaca",
                            Descricao = "Vaca"
                        },
                        new
                        {
                            Id = 40,
                            Chave = "cavalo",
                            Descricao = "Cavalo"
                        },
                        new
                        {
                            Id = 41,
                            Chave = "leao",
                            Descricao = "Leão"
                        },
                        new
                        {
                            Id = 42,
                            Chave = "tigre",
                            Descricao = "Tigre"
                        },
                        new
                        {
                            Id = 43,
                            Chave = "guepardo",
                            Descricao = "Guepardo"
                        },
                        new
                        {
                            Id = 44,
                            Chave = "lobo",
                            Descricao = "Lobo"
                        },
                        new
                        {
                            Id = 45,
                            Chave = "macaco",
                            Descricao = "Macaco"
                        },
                        new
                        {
                            Id = 46,
                            Chave = "elefante",
                            Descricao = "Elefante"
                        },
                        new
                        {
                            Id = 47,
                            Chave = "girafa",
                            Descricao = "Girafa"
                        },
                        new
                        {
                            Id = 48,
                            Chave = "morcego",
                            Descricao = "Morcego"
                        },
                        new
                        {
                            Id = 49,
                            Chave = "baleia",
                            Descricao = "Baleia"
                        },
                        new
                        {
                            Id = 50,
                            Chave = "zebra",
                            Descricao = "Zebra"
                        },
                        new
                        {
                            Id = 51,
                            Chave = "galinha",
                            Descricao = "Galinha"
                        },
                        new
                        {
                            Id = 52,
                            Chave = "pato",
                            Descricao = "Pato"
                        },
                        new
                        {
                            Id = 53,
                            Chave = "avestruz",
                            Descricao = "Avestruz"
                        },
                        new
                        {
                            Id = 54,
                            Chave = "pinguim",
                            Descricao = "Pinguim"
                        },
                        new
                        {
                            Id = 55,
                            Chave = "aguia",
                            Descricao = "Águia"
                        },
                        new
                        {
                            Id = 56,
                            Chave = "crocodilo",
                            Descricao = "Crocodilo"
                        },
                        new
                        {
                            Id = 57,
                            Chave = "cobra",
                            Descricao = "Cobra"
                        },
                        new
                        {
                            Id = 58,
                            Chave = "tartaruga",
                            Descricao = "Tartaruga"
                        },
                        new
                        {
                            Id = 59,
                            Chave = "sapo",
                            Descricao = "Sapo"
                        },
                        new
                        {
                            Id = 60,
                            Chave = "tubarao",
                            Descricao = "Tubarão"
                        },
                        new
                        {
                            Id = 61,
                            Chave = "peixe_palhaco",
                            Descricao = "Peixe-Palhaço"
                        });
                });

            modelBuilder.Entity("sistemaEspecialista_IA.Models.Regra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConclusaoFatoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDaRegra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConclusaoFatoId");

                    b.ToTable("Regras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConclusaoFatoId = 32,
                            NomeDaRegra = "R1"
                        },
                        new
                        {
                            Id = 2,
                            ConclusaoFatoId = 32,
                            NomeDaRegra = "R2"
                        },
                        new
                        {
                            Id = 3,
                            ConclusaoFatoId = 33,
                            NomeDaRegra = "R3"
                        },
                        new
                        {
                            Id = 4,
                            ConclusaoFatoId = 35,
                            NomeDaRegra = "R4"
                        },
                        new
                        {
                            Id = 5,
                            ConclusaoFatoId = 36,
                            NomeDaRegra = "R5"
                        },
                        new
                        {
                            Id = 6,
                            ConclusaoFatoId = 34,
                            NomeDaRegra = "R6"
                        },
                        new
                        {
                            Id = 7,
                            ConclusaoFatoId = 34,
                            NomeDaRegra = "R7"
                        },
                        new
                        {
                            Id = 10,
                            ConclusaoFatoId = 37,
                            NomeDaRegra = "R10"
                        },
                        new
                        {
                            Id = 11,
                            ConclusaoFatoId = 38,
                            NomeDaRegra = "R11"
                        },
                        new
                        {
                            Id = 12,
                            ConclusaoFatoId = 39,
                            NomeDaRegra = "R12"
                        },
                        new
                        {
                            Id = 13,
                            ConclusaoFatoId = 40,
                            NomeDaRegra = "R13"
                        },
                        new
                        {
                            Id = 14,
                            ConclusaoFatoId = 41,
                            NomeDaRegra = "R14"
                        },
                        new
                        {
                            Id = 15,
                            ConclusaoFatoId = 42,
                            NomeDaRegra = "R15"
                        },
                        new
                        {
                            Id = 16,
                            ConclusaoFatoId = 43,
                            NomeDaRegra = "R16"
                        },
                        new
                        {
                            Id = 17,
                            ConclusaoFatoId = 44,
                            NomeDaRegra = "R17"
                        },
                        new
                        {
                            Id = 18,
                            ConclusaoFatoId = 45,
                            NomeDaRegra = "R18"
                        },
                        new
                        {
                            Id = 19,
                            ConclusaoFatoId = 46,
                            NomeDaRegra = "R19"
                        },
                        new
                        {
                            Id = 20,
                            ConclusaoFatoId = 47,
                            NomeDaRegra = "R20"
                        },
                        new
                        {
                            Id = 21,
                            ConclusaoFatoId = 48,
                            NomeDaRegra = "R21"
                        },
                        new
                        {
                            Id = 22,
                            ConclusaoFatoId = 49,
                            NomeDaRegra = "R22"
                        },
                        new
                        {
                            Id = 23,
                            ConclusaoFatoId = 50,
                            NomeDaRegra = "R23"
                        },
                        new
                        {
                            Id = 30,
                            ConclusaoFatoId = 51,
                            NomeDaRegra = "R30"
                        },
                        new
                        {
                            Id = 31,
                            ConclusaoFatoId = 52,
                            NomeDaRegra = "R31"
                        },
                        new
                        {
                            Id = 32,
                            ConclusaoFatoId = 53,
                            NomeDaRegra = "R32"
                        },
                        new
                        {
                            Id = 33,
                            ConclusaoFatoId = 54,
                            NomeDaRegra = "R33"
                        },
                        new
                        {
                            Id = 34,
                            ConclusaoFatoId = 55,
                            NomeDaRegra = "R34"
                        },
                        new
                        {
                            Id = 40,
                            ConclusaoFatoId = 56,
                            NomeDaRegra = "R40"
                        },
                        new
                        {
                            Id = 41,
                            ConclusaoFatoId = 57,
                            NomeDaRegra = "R41"
                        },
                        new
                        {
                            Id = 42,
                            ConclusaoFatoId = 58,
                            NomeDaRegra = "R42"
                        },
                        new
                        {
                            Id = 50,
                            ConclusaoFatoId = 59,
                            NomeDaRegra = "R50"
                        },
                        new
                        {
                            Id = 60,
                            ConclusaoFatoId = 60,
                            NomeDaRegra = "R60"
                        },
                        new
                        {
                            Id = 61,
                            ConclusaoFatoId = 61,
                            NomeDaRegra = "R61"
                        });
                });

            modelBuilder.Entity("sistemaEspecialista_IA.Models.RegraCondicao", b =>
                {
                    b.Property<int>("RegraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegraId", "FatoId");

                    b.HasIndex("FatoId");

                    b.ToTable("RegraCondicoes");

                    b.HasData(
                        new
                        {
                            RegraId = 1,
                            FatoId = 1
                        },
                        new
                        {
                            RegraId = 2,
                            FatoId = 2
                        },
                        new
                        {
                            RegraId = 3,
                            FatoId = 3
                        },
                        new
                        {
                            RegraId = 4,
                            FatoId = 4
                        },
                        new
                        {
                            RegraId = 5,
                            FatoId = 5
                        },
                        new
                        {
                            RegraId = 6,
                            FatoId = 6
                        },
                        new
                        {
                            RegraId = 7,
                            FatoId = 29
                        },
                        new
                        {
                            RegraId = 10,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 10,
                            FatoId = 7
                        },
                        new
                        {
                            RegraId = 11,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 11,
                            FatoId = 8
                        },
                        new
                        {
                            RegraId = 12,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 12,
                            FatoId = 9
                        },
                        new
                        {
                            RegraId = 13,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 13,
                            FatoId = 10
                        },
                        new
                        {
                            RegraId = 14,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 14,
                            FatoId = 11
                        },
                        new
                        {
                            RegraId = 15,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 15,
                            FatoId = 18
                        },
                        new
                        {
                            RegraId = 16,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 16,
                            FatoId = 20
                        },
                        new
                        {
                            RegraId = 17,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 17,
                            FatoId = 12
                        },
                        new
                        {
                            RegraId = 18,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 18,
                            FatoId = 13
                        },
                        new
                        {
                            RegraId = 19,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 19,
                            FatoId = 14
                        },
                        new
                        {
                            RegraId = 20,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 20,
                            FatoId = 15
                        },
                        new
                        {
                            RegraId = 21,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 21,
                            FatoId = 16
                        },
                        new
                        {
                            RegraId = 22,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 22,
                            FatoId = 17
                        },
                        new
                        {
                            RegraId = 23,
                            FatoId = 32
                        },
                        new
                        {
                            RegraId = 23,
                            FatoId = 19
                        },
                        new
                        {
                            RegraId = 30,
                            FatoId = 33
                        },
                        new
                        {
                            RegraId = 30,
                            FatoId = 21
                        },
                        new
                        {
                            RegraId = 31,
                            FatoId = 33
                        },
                        new
                        {
                            RegraId = 31,
                            FatoId = 22
                        },
                        new
                        {
                            RegraId = 32,
                            FatoId = 33
                        },
                        new
                        {
                            RegraId = 32,
                            FatoId = 23
                        },
                        new
                        {
                            RegraId = 32,
                            FatoId = 24
                        },
                        new
                        {
                            RegraId = 33,
                            FatoId = 33
                        },
                        new
                        {
                            RegraId = 33,
                            FatoId = 25
                        },
                        new
                        {
                            RegraId = 34,
                            FatoId = 33
                        },
                        new
                        {
                            RegraId = 34,
                            FatoId = 26
                        },
                        new
                        {
                            RegraId = 40,
                            FatoId = 34
                        },
                        new
                        {
                            RegraId = 40,
                            FatoId = 27
                        },
                        new
                        {
                            RegraId = 41,
                            FatoId = 34
                        },
                        new
                        {
                            RegraId = 41,
                            FatoId = 28
                        },
                        new
                        {
                            RegraId = 42,
                            FatoId = 34
                        },
                        new
                        {
                            RegraId = 42,
                            FatoId = 29
                        },
                        new
                        {
                            RegraId = 50,
                            FatoId = 35
                        },
                        new
                        {
                            RegraId = 50,
                            FatoId = 30
                        },
                        new
                        {
                            RegraId = 60,
                            FatoId = 36
                        },
                        new
                        {
                            RegraId = 60,
                            FatoId = 27
                        },
                        new
                        {
                            RegraId = 61,
                            FatoId = 36
                        },
                        new
                        {
                            RegraId = 61,
                            FatoId = 31
                        });
                });

            modelBuilder.Entity("sistemaEspecialista_IA.Models.Regra", b =>
                {
                    b.HasOne("sistemaEspecialista_IA.Models.Fato", "ConclusaoFato")
                        .WithMany()
                        .HasForeignKey("ConclusaoFatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConclusaoFato");
                });

            modelBuilder.Entity("sistemaEspecialista_IA.Models.RegraCondicao", b =>
                {
                    b.HasOne("sistemaEspecialista_IA.Models.Fato", "Fato")
                        .WithMany()
                        .HasForeignKey("FatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaEspecialista_IA.Models.Regra", "Regra")
                        .WithMany("Condicoes")
                        .HasForeignKey("RegraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fato");

                    b.Navigation("Regra");
                });

            modelBuilder.Entity("sistemaEspecialista_IA.Models.Regra", b =>
                {
                    b.Navigation("Condicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
